### PR TITLE
update python and package

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
## Proposed changes

- update minimum python from 3.0 to 3.6
- use pyreadline3 instead of pyreadline
- restrict pyreadline3 to windows only

resolve https://github.com/iamtalhaasghar/yewtube/issues/8
resolve https://github.com/iamtalhaasghar/yewtube/issues/10

## Types of changes

_Put an `x` in the boxes that apply_

- Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-  Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the CONTRIBUTING.md
- [x] Lint and unit tests pass locally with my changes
-  I have added tests that prove my fix is effective or that my feature works
-  I have added necessary documentation (if appropriate)
-  Any dependent changes have been merged and published in downstream modules

## Further comments

`python_requires` option require setuptools >= 24.2.0 or pip >= 9.0.0, see 

https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#id49

### CODE REVIEW

**Comment by rachmadaniHaryono** [comment]
pyreadline is not compatible with linux

i can't find original pyreadline repo but updated repo also mention that it is not compatible with linux

https://github.com/pyreadline/pyreadline/blob/4e4b7b468cfdf2dfef8e2c8c695a64e96c514213/setup.py#L18-L19

**Comment by iamtalhaasghar** [comment]
> pyreadline is not compatible with linux
> 
> i can't find original pyreadline repo but updated repo also mention that it is not compatible with linux
> 
> https://github.com/pyreadline/pyreadline/blob/4e4b7b468cfdf2dfef8e2c8c695a64e96c514213/setup.py#L18-L19

@rachmadaniHaryono Had to remove `platform_system=="Windows"` from `install_requires` as pipx complains about it. I will investigate `pyreadline` compatibility issue later.

**Comment by rachmadaniHaryono** [comment]
maybe because you forget to add comma after `'pyreadline ; platform_system=="Linux"'`

**Comment by iamtalhaasghar** [comment]
Ah thanks, will update it,

**Pull request merged**
